name: Keepalive Ping

on:
  schedule:
    # Every 5 minutes (best-effort by GitHub)
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

permissions: {}

concurrency:
  group: keepalive-ping
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      # Configure in: Settings → Secrets and variables → Actions → Variables
      # KEEPALIVE_URLS can be a single URL or multiple, comma-separated.
      KEEPALIVE_URLS: ${{ vars.KEEPALIVE_URLS }}
      USER_AGENT: VCO-KeepAlive/1.0
    steps:
      - name: Ping keepalive URLs
        shell: bash
        run: |
          set -euo pipefail

          URLS="${KEEPALIVE_URLS:-https://officeonevco.in/health}"
          echo "Configured URLs: $URLS"

          # Normalize: split by comma/newline, trim, drop empties
          mapfile -t URL_LIST < <(printf "%s\n" "$URLS" \
            | tr ',' '\n' \
            | sed 's/^ *//;s/ *$//' \
            | sed '/^$/d')

          if [[ ${#URL_LIST[@]} -eq 0 ]]; then
            echo "No URLs found to ping. Set KEEPALIVE_URLS in Actions Variables."
            exit 1
          fi

          any_success=0

          for raw in "${URL_LIST[@]}"; do
            url="$raw"
            # Ensure scheme
            if [[ "$url" != http*://* ]]; then
              url="https://$url"
            fi

            echo "Pinging: $url"

            success=0
            # Up to 3 attempts per URL
            for attempt in 1 2 3; do
              code=$(curl -sS -o /dev/null -w "%{http_code}" \
                -A "$USER_AGENT" \
                --connect-timeout 4 \
                --max-time 8 \
                "$url" || true)
              echo "Attempt $attempt → HTTP $code"

              if [[ "$code" =~ ^[0-9]+$ ]] && [ "$code" -lt 400 ]; then
                success=1
                any_success=1
                echo "::notice title=Ping Succeeded::$url responded with $code"
                break
              fi
              sleep 5
            done

            if [ $success -eq 0 ]; then
              echo "::warning title=Ping Failed::All attempts failed for $url"
            fi
          done

          # Overall result: succeed if at least one URL responded < 400
          if [ $any_success -eq 0 ]; then
            echo "::error::No keepalive endpoints succeeded"
            exit 1
          fi

          echo "Keepalive completed."
